import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/Navbar";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="class">
      <body className={inter.className}>
        <div className="relative  flex justify-center items-center">
          <NavbarDemo/>
        </div>

        {children}
        <div> <Footer/></div>
      </body>
    </html>
  );
}
